#!/usr/bin/env python3
"""Archive/check original extension cases and their independent native outputs."""

import argparse
import copy
import gzip
import hashlib
import json
import math
import tempfile
from collections import Counter
from pathlib import Path

import ezjww
from check_compatibility import close, is_setting, read_dxf_tags
from make_extension_cases import cases

ROOT = Path(__file__).resolve().parents[2]
FIXTURES = ROOT / "jww_samples/writer/extensions"
CASE_NAMES = (
    "sxf_colors",
    "sxf_linetypes",
    "solid",
    "ellipse",
    "dimension",
    "block",
    "text_auto_end",
)


def sha(data):
    return hashlib.sha256(data).hexdigest()


def archive(run, destination):
    report = json.loads((run / "native.json").read_text())
    assert report["complete"] and [c["id"] for c in report["cases"]] == list(CASE_NAMES)
    runner = (run / "native_roundtrip_wine.py").read_bytes()
    assert sha(runner) == report["script_sha256"]
    destination.mkdir(parents=True, exist_ok=False)
    files = {
        "native.json": (run / "native.json").read_bytes(),
        "native_roundtrip_wine.py": runner,
        "make_extension_cases.py": (
            ROOT / "scripts/jww/make_extension_cases.py"
        ).read_bytes(),
    }
    for event in report["cases"]:
        assert event["complete"] and event["input_unchanged"]
        assert all(
            value == 0 for key, value in event.items() if key.endswith("exit_code")
        )
        for name, record in event["files"].items():
            # Do not copy any application files, prefixes or fonts.
            assert Path(name).name == name and Path(name).suffix in {
                ".jww",
                ".dxf",
                ".png",
            }
            data = (run / "runtime" / name).read_bytes()
            assert sha(data) == record["sha256"] and len(data) == record["size"]
            files[name] = data
    manifest = {
        "cases": list(CASE_NAMES),
        "files": {},
        "license": "Original drawings and tools: MIT; screenshots include Jw_cad UI. No application binaries or fonts.",
    }
    for name, data in sorted(files.items()):
        stored = name if name.endswith(".png") else name + ".gz"
        encoded = data if name.endswith(".png") else gzip.compress(data, mtime=0)
        (destination / stored).write_bytes(encoded)
        manifest["files"][name] = {
            "path": stored,
            "sha256": sha(data),
            "size": len(data),
            "stored_sha256": sha(encoded),
        }
    (destination / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")


def check(directory=FIXTURES):
    manifest = json.loads((directory / "manifest.json").read_text())
    assert manifest["cases"] == list(CASE_NAMES)
    files = {}
    for name, item in manifest["files"].items():
        data = (directory / item["path"]).read_bytes()
        assert sha(data) == item["stored_sha256"], name
        if item["path"].endswith(".gz"):
            data = gzip.decompress(data)
        assert sha(data) == item["sha256"] and len(data) == item["size"], name
        files[name] = data
    log = json.loads(files["native.json"])
    assert (
        log["complete"]
        and sha(files["native_roundtrip_wine.py"]) == log["script_sha256"]
    )
    for event in log["cases"]:
        assert event["complete"] and event["input_unchanged"]
        assert all(
            value == 0 for key, value in event.items() if key.endswith("exit_code")
        )
        for name, info in event["files"].items():
            assert sha(files[name]) == info["sha256"]
    result = {}
    with tempfile.TemporaryDirectory(prefix="ezjww-extension-check-") as folder:
        folder = Path(folder)
        for name, data in files.items():
            if name.endswith(".jww"):
                (folder / name).write_bytes(data)
        for name, drawing in cases().items():
            assert drawing.to_jww_bytes() == files[name + ".jww"], (
                name + ": regenerated bytes"
            )
            source = ezjww.read_document(str(folder / (name + ".jww")))
            expected = copy.deepcopy(source["entities"])
            if name == "sxf_colors":
                expected[2]["base"]["pen_color"] = 1  # Reserved 100 is normalized.
            if name == "sxf_linetypes":
                expected[4]["base"]["pen_style"] = 9  # Reserved 30 is normalized.
            block_defs = copy.deepcopy(source["block_defs"])
            if name == "block":
                for block in block_defs:
                    block["name"] += "@@SfigorgFlag@@4"
                for entities in [expected, *(b["entities"] for b in block_defs)]:
                    for entity in entities:
                        if entity["type"] == "BLOCK":
                            entity["block_name"] += "@@SfigorgFlag@@4"
            measurements = []
            for suffix in ("_saved", "_reopened"):
                parsed = ezjww.read_document(str(folder / (name + suffix + ".jww")))
                entities = [e for e in parsed["entities"] if not is_setting(e)]
                assert len(parsed["entities"]) - len(entities) == 6
                assert len(entities) == len(expected), name
                if name == "text_auto_end":
                    errors = []
                    for actual, want in zip(entities, expected):
                        delta = math.hypot(
                            actual["end_x"] - want["end_x"],
                            actual["end_y"] - want["end_y"],
                        )
                        assert delta <= want["size_x"], (name, delta)
                        errors.append(delta)
                        actual["end_x"], actual["end_y"] = want["end_x"], want["end_y"]
                    measurements.append(errors)
                assert close(entities, expected), name + suffix + ": entities"
                assert close(parsed["block_defs"], block_defs), (
                    name + suffix + ": definitions"
                )
                assert close(
                    parsed["header"]["palette"], source["header"]["palette"]
                ), name + ": palette"
                assert close(
                    parsed["header"]["text_presets"], source["header"]["text_presets"]
                ), name + ": presets"
                if name == "sxf_linetypes":
                    a, b = (
                        copy.deepcopy(parsed["header"]["line_types"]),
                        copy.deepcopy(source["header"]["line_types"]),
                    )
                    # Slot 30 is unused/reserved and contains native scratch values.
                    a["sxf"][0] = b["sxf"][0]
                    assert close(a, b), "active line pattern tables"
            tags = read_dxf_tags(files[name + "_reopened.dxf"])
            counts = dict(Counter(e[0] for e in tags))
            if name == "sxf_colors":
                assert [int(e[62]) for e in tags] == [
                    132,
                    211,
                    132,
                    18,
                    8,
                    9,
                    18,
                    18,
                    34,
                    164,
                    230,
                ]
                assert not any(420 in e for e in tags)  # Native exporter maps to ACI.
            if name == "ellipse":
                assert counts == {
                    "LINE": 102
                }  # Native DXF tessellates; ezjww emits ELLIPSE.
                assert {e["type"] for e in drawing.to_dxf()["entities"]} == {"ELLIPSE"}
            if name == "block":
                assert counts == {"INSERT": 2}
            if name == "solid":
                assert counts["SOLID"] == 2
            item = {
                "entities": len(expected),
                "block_definitions": len(block_defs),
                "native_dxf_entities": counts,
            }
            if measurements:
                item["endpoint_errors_mm"] = measurements
            result[name] = item
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--directory", type=Path, default=FIXTURES)
    parser.add_argument("--archive-run", type=Path)
    parser.add_argument("--report", type=Path)
    args = parser.parse_args()
    if args.archive_run:
        archive(args.archive_run, args.directory)
    result = check(args.directory)
    if args.report:
        args.report.write_text(json.dumps(result, indent=2) + "\n")
    print(
        "Writer extension native evidence passed: 7 cases, both native saves and DXF outputs"
    )


if __name__ == "__main__":
    main()
