"""Reproduce generated bytes and inspect recorded independent native evidence."""

import importlib.util
import sys
from pathlib import Path


def test_native_extension_evidence():
    scripts = Path(__file__).resolve().parents[2] / "scripts/jww"
    # The script also runs directly; its sibling helpers are used unchanged.
    sys.path.insert(0, str(scripts))
    try:
        spec = importlib.util.spec_from_file_location(
            "check_extensions", scripts / "check_extensions.py"
        )
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        result = module.check()
        assert len(result) == 7
    finally:
        sys.path.remove(str(scripts))
